Proto/2024/11/27
fsi-la-inf/Protokolle pull request #5
Opened 2024-11-27 21:47 UTC by PhoebeMea

2024-11-28 10:19 UTC, tb1402 approved these changes
Top

2024-11-28 10:21 UTC, motrellin requested changes

2024-11-28 10:21 UTC, motrellin commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +    responsible: Fabian, Phoebe, Adrian
```suggestion
      Adrian schreibt noch eine Mail, dass diejenigen, die kommen, sich zuvor
      eine Schließberechtigung für das Informatikgebäude beantragen, und zudem
      über das Schrottwichteln in Kenntnis gesetzt werden.
      
      Jakob kümmert sich um die restlichen Ankündigungen.
    responsible: Fabian, Phoebe, Adrian, Jakob
```
Das hatten wir noch gesagt, glaube.

2024-11-28 10:21 UTC, motrellin commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +      Dinge aufzubewahren.
```suggestion
    result: |
      Wir bekommen möglicherweise einen Schrank im CIP-Pool des 5.Stocks zugeteilt, um darin
      Dinge aufzubewahren. Das ist aber noch nicht final abgeklärt und wir müssen dran bleiben.
    responsible: Anna
```

2024-11-28 10:21 UTC, motrellin commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +    responsible: Ole, Adrian
```suggestion
     (Fabian) und FSI Informatik (Ole) nachfragen, ob sie einen Raum für uns
     hätten/wüssten oder bereit wären, ihren Raum mit uns zu teilen.
    responsible: Ole, Fabian
```
Vlt. kurzer Check: Ich hatte da @FJCraft1 im Kopf und nicht @Adrian-001 , aber das wissen die Leute sicherlich am besten :)

2024-11-28 10:21 UTC, motrellin commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +     vorgeschlagen. Wird ein längeres Projekt. Alle finden die Idee gut.
```suggestion
     Adrian hat uns ein neues Website-Design vorgesellt. Es wurden Verbesserungen
     vorgeschlagen. Wird ein längeres Projekt. Alle finden die Idee gut.
```

2024-11-28 10:44 UTC, Adrian-001 commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +    responsible: Ole, Adrian
Dachte ich auch aber glaube, dass wir das eh zusammen machen werden.

2024-11-28 11:59 UTC, motrellin commented on docs/_posts/2024-11-27-sitzung-5-3.md
> +    responsible: Ole, Adrian
ok, dann lassen wir's, wie es ist.

2024-11-29 08:29 UTC, FJCraft1 approved these changes

2024-11-29 10:57 UTC, Ofenzucchin approved these changes

2024-11-29 21:05 UTC, motrellin approved these changes

2024-11-29 21:05 UTC, merged