Proto Sitzung 12-11
fsi-la-inf/Protokolle pull request #7
Opened 2024-12-11 18:16 UTC by tb1402

2024-12-11 18:31 UTC, Adrian-001 approved these changes

2024-12-11 18:36 UTC, motrellin requested changes

2024-12-17 14:27 UTC, motrellin commented on docs/_posts/2024-12-11-sitzung-5-4.md
> +      Probleme zwecks Terminüberschneidungen bei Sitzungen lassen sich über Pläne regeln.
@Adrian-001 kannst du das bestätigen und ggf. die Suggestion gleich committen? Also ob das dem Stand in der Sitzung matcht? War glaube ich dein Bereich.

2025-01-02 18:26 UTC, Adrian-001 approved these changes

2025-01-02 18:27 UTC, Adrian-001 approved these changes

2025-01-03 19:49 UTC, motrellin approved these changes

2025-01-03 19:50 UTC, motrellin commented
Ich merge das die Tage, wenn keine weiteren Einwände kommen. Gerne aber auch explizite Approves geben.

2025-01-07 16:43 UTC, merged